### ISSUE TITLE
run problem : yarn run start:server 

### ISSUE THREAD

**Issue by KamiSec** [cisagov/RedEye#13]
environment:
ubuntu:20.04
nodejs:16.17.1
npm:8.19.2
yarn:3.2.3

The following error occurs when I run the `yarn install` command:
```
root:~/RedEye# yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @nrwl/cypress@npm:14.6.5 [63507] doesn't provide nx (p10390), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/cypress@npm:14.6.5 [63507] doesn't provide typescript (p12f21), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/cypress@npm:14.6.5 [63507] doesn't provide typescript (p6345b), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @nrwl/cypress@npm:14.6.5 [63507] doesn't provide typescript (pfc203), requested by ts-loader
➤ YN0002: │ @nrwl/cypress@npm:14.6.5 [7a45f] doesn't provide nx (p1f374), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/cypress@npm:14.6.5 [7a45f] doesn't provide typescript (p1ce2c), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/cypress@npm:14.6.5 [7a45f] doesn't provide typescript (p88b83), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @nrwl/cypress@npm:14.6.5 [7a45f] doesn't provide typescript (p52358), requested by ts-loader
➤ YN0002: │ @nrwl/devkit@npm:14.6.3 [7d709] doesn't provide typescript (p4b372), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/devkit@npm:14.6.3 [f7f79] doesn't provide typescript (pd13ca), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/devkit@npm:14.6.5 [466ed] doesn't provide typescript (p952f2), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/devkit@npm:14.6.5 [7a45f] doesn't provide typescript (p88aeb), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/devkit@npm:14.6.5 [e712c] doesn't provide typescript (p121bf), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/eslint-plugin-nx@npm:14.6.3 [7a45f] doesn't provide eslint (pcdd36), requested by @typescript-eslint/utils
➤ YN0002: │ @nrwl/eslint-plugin-nx@npm:14.6.3 [7a45f] doesn't provide nx (p3f0ed), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/jest@npm:14.6.3 doesn't provide nx (p7bd51), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/jest@npm:14.6.3 doesn't provide typescript (paa32c), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/jest@npm:14.6.5 doesn't provide nx (p51599), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/jest@npm:14.6.5 doesn't provide typescript (p68cd3), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/js@npm:14.6.3 doesn't provide nx (p2cb88), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/js@npm:14.6.5 doesn't provide nx (p8ee91), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/linter@npm:14.6.3 [7a45f] doesn't provide typescript (pe0811), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/linter@npm:14.6.3 [89c3e] doesn't provide typescript (pbe7e7), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/linter@npm:14.6.5 [ecbee] doesn't provide typescript (pf9585), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/node@npm:14.6.5 doesn't provide @types/node (pf093b), requested by ts-node
➤ YN0002: │ @nrwl/node@npm:14.6.5 doesn't provide nx (p3e1ba), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/node@npm:14.6.5 doesn't provide typescript (p931a2), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @nrwl/node@npm:14.6.5 doesn't provide typescript (p42906), requested by ts-loader
➤ YN0002: │ @nrwl/node@npm:14.6.5 doesn't provide typescript (p3b16b), requested by ts-node
➤ YN0002: │ @nrwl/web@npm:14.6.5 doesn't provide @types/node (pbf886), requested by ts-node
➤ YN0002: │ @nrwl/web@npm:14.6.5 doesn't provide nx (p66ace), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/web@npm:14.6.5 doesn't provide typescript (pd976f), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @nrwl/web@npm:14.6.5 doesn't provide typescript (p796a9), requested by ts-loader
➤ YN0002: │ @nrwl/web@npm:14.6.5 doesn't provide typescript (p032d9), requested by ts-node
➤ YN0002: │ @nrwl/web@npm:14.6.5 doesn't provide typescript (p7ef8a), requested by rollup-plugin-typescript2
➤ YN0002: │ @nxext/vite@npm:14.0.0 [7a45f] doesn't provide nx (p23fe6), requested by @nrwl/devkit
➤ YN0002: │ @types/testing-library__react@npm:10.2.0 doesn't provide react (p31675), requested by @testing-library/react
➤ YN0002: │ @types/testing-library__react@npm:10.2.0 doesn't provide react-dom (p45428), requested by @testing-library/react
➤ YN0002: │ redeye@workspace:. doesn't provide @babel/core (p5e601), requested by @emotion/babel-plugin
➤ YN0002: │ redeye@workspace:. doesn't provide @babel/plugin-syntax-flow (p48cba), requested by eslint-plugin-flowtype
➤ YN0002: │ redeye@workspace:. doesn't provide @babel/plugin-transform-react-jsx (pbf514), requested by eslint-plugin-flowtype
➤ YN0002: │ redeye@workspace:. doesn't provide @blueprintjs/docs-theme (p9d6a0), requested by blueprint-styler
➤ YN0002: │ redeye@workspace:. doesn't provide @blueprintjs/icons (p9e3bc), requested by blueprint-styler
➤ YN0002: │ redeye@workspace:. doesn't provide @blueprintjs/table (p457d2), requested by blueprint-styler
➤ YN0002: │ redeye@workspace:. doesn't provide @blueprintjs/timezone (pcdff1), requested by blueprint-styler
➤ YN0002: │ redeye@workspace:. doesn't provide @testing-library/dom (p4b37a), requested by @testing-library/user-event
➤ YN0002: │ redeye@workspace:. doesn't provide eslint-plugin-n (p61d4a), requested by eslint-config-standard
➤ YN0060: │ redeye@workspace:. provides mobx-keystone (p05af7) with version 1.0.0, which doesn't satisfy what mk-gql requests
➤ YN0060: │ redeye@workspace:. provides prettier (p92f8b) with version 2.5.1, which doesn't satisfy what @nrwl/workspace requests
➤ YN0060: │ redeye@workspace:. provides react (pca4bc) with version 18.2.0, which doesn't satisfy what @blueprintjs/core and some of its descendants request
➤ YN0060: │ redeye@workspace:. provides react (p15ae2) with version 18.2.0, which doesn't satisfy what @blueprintjs/datetime and some of its descendants request
➤ YN0060: │ redeye@workspace:. provides react (pe4698) with version 18.2.0, which doesn't satisfy what @blueprintjs/popover2 and some of its descendants request
➤ YN0060: │ redeye@workspace:. provides react (p81fea) with version 18.2.0, which doesn't satisfy what react-resize-detector requests
➤ YN0060: │ redeye@workspace:. provides react-dom (p22dbf) with version 18.2.0, which doesn't satisfy what react-resize-detector requests
➤ YN0002: │ redeye@workspace:. doesn't provide rollup (p85155), requested by rollup-plugin-auto-external
➤ YN0060: │ redeye@workspace:. provides vite (pacda5) with version 3.1.3, which doesn't satisfy what @nxext/vite requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 377ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 3m 25s
➤ YN0000: ┌ Link step
➤ YN0007: │ cypress@npm:10.9.0 must be built because it never has been before or the last one failed
➤ YN0007: │ nodemon@npm:2.0.15 must be built because it never has been before or the last one failed
➤ YN0007: │ playwright-webkit@npm:1.25.2 must be built because it never has been before or the last one failed
➤ YN0007: │ @carbon/icons-react@npm:10.44.0 [7a45f] must be built because it never has been before or the last one failed
➤ YN0007: │ type-graphql@npm:1.1.1 [7a45f] must be built because it never has been before or the last one failed
➤ YN0007: │ @parcel/watcher@npm:2.0.4 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.22.7 must be built because it never has been before or the last one failed
➤ YN0007: │ better-sqlite3@npm:7.6.2 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.15.9 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.22.7 must be built because it never has been before or the last one failed
➤ YN0007: │ @apollo/protobufjs@npm:1.2.4 must be built because it never has been before or the last one failed
➤ YN0007: │ redeye@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ nx@npm:14.6.3 [f7f79] must be built because it never has been before or the last one failed
➤ YN0007: │ nx@npm:14.6.5 [4a848] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1m 53s
➤ YN0000: Done with warnings in 5m 20s
```
run `yarn release:all`
```
✔  nx run models:build  [remote cache]
    ✔  nx run graph:build  [remote cache]
    ✔  nx run parser:build  [remote cache]
    ✔  nx run client:build:production  [remote cache]
    ✔  nx run server:build  [remote cache]

    ✖  nx run parser:release-all
       >  NX   Running target release for project parser and 2 task(s) it depends on
       
        
       
       > nx run parser:build  [existing outputs match the cache, left as is]
       
       Compiling with SWC for parser...
       Successfully compiled: 41 files with swc (58.2ms)
       
       > nx run parser:release --platform=mac
       
       > pkg@5.8.0
       > Fetching base Node.js binaries to PKG_CACHE_PATH
       
       
       > Error! Binary hash does NOT match.
       
        >  NX   ERROR: Something went wrong in run-commands - Command failed: pkg dist/packages/cs-parser/package.json -t node16-mac -o release/mac/parsers/cs-parser
       
          Pass --verbose to see the stacktrace.
       
       
        
       
        >  NX   Running target "parser:release" failed
       
          Failed tasks:
          
          - parser:release
          
          Hint: run the command with --verbose for more details.
       
       
        >  NX   ERROR: Something went wrong in run-commands - Command failed: yarn nx release parser --platform mac
       
          Pass --verbose to see the stacktrace.
       

    ✖  nx run server:release-all
       >  NX   Running target release for project server and 5 task(s) it depends on
       
        
       
       > nx run server:build  [existing outputs match the cache, left as is]
       
       Compiling with SWC for server...
       Successfully compiled: 56 files with swc (63.79ms)
       
       > nx run server:release --platform=mac
       
       > pkg@5.8.0
       > Fetching base Node.js binaries to PKG_CACHE_PATH
       
       
       node:internal/fs/utils:347
           throw err;
           ^
       
       Error: ENOENT: no such file or directory, stat '/root/.pkg-cache/v3.4/fetched-v16.16.0-macos-x64.downloading'
           at Object.statSync (node:fs:1588:3)
           at Object.statSync (/root/RedEye-cisa/node_modules/graceful-fs/polyfills.js:318:34)
           at statSync (/root/RedEye-cisa/node_modules/fs-extra/lib/util/stat.js:10:52)
           at getStatsSync (/root/RedEye-cisa/node_modules/fs-extra/lib/util/stat.js:24:19)
           at Object.checkPathsSync (/root/RedEye-cisa/node_modules/fs-extra/lib/util/stat.js:49:33)
           at Object.moveSync (/root/RedEye-cisa/node_modules/fs-extra/lib/move-sync/move-sync.js:14:28)
           at WriteStream.<anonymous> (/root/RedEye-cisa/node_modules/pkg-fetch/lib-es5/utils.js:90:56)
           at WriteStream.<anonymous> (node:internal/util:445:5)
           at WriteStream.onclose (node:internal/streams/end-of-stream:147:14)
           at WriteStream.emit (node:events:513:28) {
         errno: -2,
         syscall: 'stat',
         code: 'ENOENT',
         path: '/root/.pkg-cache/v3.4/fetched-v16.16.0-macos-x64.downloading'
       }
       
        >  NX   ERROR: Something went wrong in run-commands - Command failed: pkg dist/applications/server/package.json -t node16-mac -o release/mac/RedEye
       
          Pass --verbose to see the stacktrace.
       
       
        
       
        >  NX   Running target "server:release" failed
       
          Failed tasks:
          
          - server:release
          
          Hint: run the command with --verbose for more details.
       
       
        >  NX   ERROR: Something went wrong in run-commands - Command failed: yarn nx release server --platform mac
       
          Pass --verbose to see the stacktrace.
       

 —————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target release-all for 2 projects and 5 task(s) they depend on (12s)
 
    ✔    5/7 succeeded [5 read from cache]
 
    ✖    2/7 targets failed, including the following:
         - nx run parser:release-all
         - nx run server:release-all
 
   Nx Cloud made it possible to reuse 5 tasks: https://nx.app/runs/mXmOCfDmj8
```
run `yarn run start:server`
```
root:~/RedEye# yarn run start:server

> nx run server:serve

Compiling with SWC for models...
Successfully compiled: 27 files with swc (134.79ms)
Compiling with SWC for parser...
Successfully compiled: 41 files with swc (92.14ms)

 >  NX   inotify_add_watch on '/root/RedEye-cisa/node_modules/@faker-js/faker/dist/types/locales/hy/color' failed: No space left on device

   Pass --verbose to see the stacktrace.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "server:serve" failed

   Failed tasks:
   
   - server:serve
   
   Hint: run the command with --verbose for more details.

   See Nx Cloud run details at https://nx.app/runs/Ck14JFu42J
```

**Comment by GoldingAustin** [comment]
Thanks for the detailed logs, really appreciate it! It looks like there are two different problems happening:

1. With `yarn run release:all`
   - I'm seeing `Error! Binary hash does NOT match.`
   - Are you able to run `yarn run release --platform linux` or does any release fail to build?
2. With `yarn run start:server`
   - I'm seeing `failed: No space left on device` in you stack trace. Is your host out of disk space?

**Comment by pypygeek** [comment]
> Thanks for the detailed logs, really appreciate it! It looks like there are two different problems happening:
> 
> 1. With `yarn run release:all`
>    
>    * I'm seeing `Error! Binary hash does NOT match.`
>    * Are you able to run `yarn run release --platform linux` or does any release fail to build?
> 2. With `yarn run start:server`
>    
>    * I'm seeing `failed: No space left on device` in you stack trace. Is your host out of disk space?

`yarn run start:server` -> I also get the `failed: No space left on device` error
I have 90 GB of free disk space, how much more do I need?

**Comment by JO-JO-Lin** [comment]
I also encountered the same problem, is there any solution? Thanks.

**Comment by Uchedanieln** [comment]
Optional []()

**Comment by sang2925** [comment]
> > Thanks for the detailed logs, really appreciate it! It looks like there are two different problems happening:
> > 
> > 1. With `yarn run release:all`
> >    
> >    * I'm seeing `Error! Binary hash does NOT match.`
> >    * Are you able to run `yarn run release --platform linux` or does any release fail to build?
> > 2. With `yarn run start:server`
> >    
> >    * I'm seeing `failed: No space left on device` in you stack trace. Is your host out of disk space?
> 
> `yarn run start:server` -> I also get the `failed: No space left on device` error I have 90 GB of free disk space, how much more do I need?

Could you provide your environment details? I will look into troubleshooting this.

**Comment by pypygeek** [comment]
> > > Thanks for the detailed logs, really appreciate it! It looks like there are two different problems happening:
> > > 
> > > 1. With `yarn run release:all`
> > >    
> > >    * I'm seeing `Error! Binary hash does NOT match.`
> > >    * Are you able to run `yarn run release --platform linux` or does any release fail to build?
> > > 2. With `yarn run start:server`
> > >    
> > >    * I'm seeing `failed: No space left on device` in you stack trace. Is your host out of disk space?
> > 
> > 
> > `yarn run start:server` -> I also get the `failed: No space left on device` error I have 90 GB of free disk space, how much more do I need?
> 
> Could you provide your environment details? I will look into troubleshooting this.

[Virtualbox 5.2.4]
OS : Ubuntu 18.04.5 LTS Server
CPU : 2Core
MEM : 2GB
HDD : 100GB
