### ISSUE TITLE
code: 'ERR_DLOPEN_FAILED' on Windows & Linux

### ISSUE THREAD

**Issue by huornlmj** [cisagov/RedEye#170]
**Describe the bug**
Receiving an error when trying to run on Windows
```
No config file found, using defaults
No parsers specified in config, only .redeye files can be uploaded
Error: C:\Users\user\AppData\Local\Temp\pkg\6090aceae56dd7014cf4fb03930bc2a1031f87eb0a8f1f8ce4b2d9e7f1524366\better-sqlite3\build\Release\better_sqlite3.node is not a valid Win32 application.
C:\Users\user\AppData\Local\Temp\pkg\6090aceae56dd7014cf4fb03930bc2a1031f87eb0a8f1f8ce4b2d9e7f1524366\better-sqlite3\build\Release\better_sqlite3.node
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (C:\snapshot\RedEye\node_modules\bindings\bindings.js:112:48)
    at new Database (C:\snapshot\RedEye\node_modules\better-sqlite3\lib\database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (C:\snapshot\RedEye\node_modules\knex\lib\dialects\better-sqlite3\index.js:12:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Cleaning up... {
  type: 'error.platform.SERVER_MACHINE.loadDatabase:invocation[0]',
  data: undefined,
  toString: [Function (anonymous)]
}
```
Receiving an error when trying to run on Ubuntu 22.04.2 Linux
```
$ ./RedEye -r -p password
No config file found, using defaults
No parsers specified in config, only .redeye files can be uploaded
Error: /tmp/pkg/6090aceae56dd7014cf4fb03930bc2a1031f87eb0a8f1f8ce4b2d9e7f1524366/better-sqlite3/build/Release/better_sqlite3.node: invalid ELF header
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/snapshot/RedEye/node_modules/bindings/bindings.js:112:48)
    at new Database (/snapshot/RedEye/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/snapshot/RedEye/node_modules/knex/lib/dialects/better-sqlite3/index.js:12:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Cleaning up... {
  type: 'error.platform.SERVER_MACHINE.loadDatabase:invocation[0]',
  data: undefined,
  toString: [Function (anonymous)]
}

```

**To Reproduce**
1. Download latest version and extract.
2. Run `RedEye --redTeam --password REDACTED`
3. Observe error

**Expected behavior**
Work

**Desktop (please complete the following information):**
- OS: Windows 10 & Ubuntu 22.04.2 LTS
- Browser: N/A
- Version: [RedEye@0.9.0](https://github.com/cisagov/RedEye/releases/tag/v0.9.0)

**Comment by GoldingAustin** [comment]
Thanks for the bug report! I was able to reproduce the issue on Windows. The latest release fixed the issue in my testing; let me know if you still see issues with this release! https://github.com/cisagov/RedEye/releases/tag/v0.9.1
